### ISSUE TITLE
Compatible with Python3?

### ISSUE THREAD

**Issue by wbensvage** [mattloper/opendr#19]
I was using Python3 and tried to install OpenDR via pip. But I failed and found opendr now seems only compatible with Python 2? So can I know is there any plan to move opendr forward to Python 3? And is there any way I can overcome this currently?

**Comment by hset911** [comment]
anyone could reply this?

**Comment by SelvamArul** [comment]
There is an updated version of opendr [here](https://github.com/polmorenoc/opendr) but this one is not official though.

**Comment by tejanmehndiratta15** [comment]
I tried installing opendr on python 3 on anaconda using both pip and conda, but failed. Can anyone help me on this? I also tried finding .whl file for opendr, but couldn't.

**Comment by Hosseinhashemiir** [comment]
@akanazawa  there is no problem with Matplotlib codes but I have the same error like @tejanmehndiratta15  
I would be thankful for any suggestion or solution.

**Comment by AnirudhPuligandla** [comment]
@SelvamArul  Do you know how we can install that? Thanks in advance

**Comment by SelvamArul** [comment]
@AnirudhPuligandla Could you please elaborate on your question? Sorry, I didn't get what you mean by install. It is just a python package. Noting to install there.

**Comment by AnirudhPuligandla** [comment]
@SelvamArul Sorry for the vague question! Actually I am testing some code that uses opendr to display images and a 3D mesh. So, i have this modern opendr package in my PYTHONPATH with the other requirements installed. But, i am not sure if this package can readily replace opendr (in terms of fucntions to open a window, display etc.) as i still encounter the same error "no module named opendr". I am using python3.5

I hope that is clear.

Thanks

**Comment by neonb88** [comment]
@SelvamArul To clarify, have you gotten it working in python3?  Also, did you manage to do everything with PYTHONPATH?  I'm not sure how python3 absolute imports works under the hood, nor how pip and conda do

**Comment by SelvamArul** [comment]
ya, this [fork](https://github.com/polmorenoc/opendr) is python3 compatible. I have forked it further to make to compatible with latest versions of NumPy and Scipy, and few other bug fixes related to wrong dimension specification while reading out the rendered images from OpenGL. You can find my [fork](https://github.com/SelvamArul/opendr) here. 

Regrading the PYTHONPATH, I didn't get your question. Could you please describe your issue in detail?

**Comment by tszhang97** [comment]
> ya, this [fork](https://github.com/polmorenoc/opendr) is python3 compatible. I have forked it further to make to compatible with latest versions of NumPy and Scipy, and few other bug fixes related to wrong dimension specification while reading out the rendered images from OpenGL. You can find my [fork](https://github.com/SelvamArul/opendr) here.
> 
> Regrading the PYTHONPATH, I didn't get your question. Could you please describe your issue in detail?

I used your fork and met this error:
AttributeError: 'ColoredRenderer' object has no attribute 'vbo_verts_face'
Could you help me find out what's wrong?

**Comment by erezposner** [comment]
@willie1997 have you managed to solve this issue?

**Comment by salmedina** [comment]
I was finally able to install OpenDR through PIP on Python 3.7 in a conda environment. What worked like magic for me was installing _libosmesa6-dev_:
```
conda create -n smpl python=3.7
conda activate smpl
conda install numpy
conda install chumpy
conda install -c conda-forge opencv

sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
sudo apt-get install libosmesa6-dev
pip install opendr
```
Hope this helps!

**Comment by erezposner** [comment]
@salmedina  are you working under linux/windows?

**Comment by salmedina** [comment]
@erezposner This was on Ubuntu 18.04.3 LTS

**Comment by WilliamWang1994** [comment]
Maybe you can try the modern version from [polmorenoc](https://github.com/polmorenoc/opendr).
it seem like work on windows.

**Comment by yohanshin** [comment]
@salmedina Following your description, it perfectly works on my ubuntu-18.04 LTS too! Just instead, since conda doesn't have their chumpy cloud, try pip install chumpy

**Comment by yutao007** [comment]
conda install chumpy   ------wrong

**Comment by bmquynhlinh** [comment]
> 

This solution works for virtual env python3.10 too
`
sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
sudo apt-get install libosmesa6-dev
pip install opendr
`

**Comment by Qiicx** [comment]
I was finally able to install OpenDR after upgrade Cpython
`pip install --upgrade Cython`
